module.exports = {
    CONSTANTS: {
        //ALGUNOS CODIGOS DE ERRORES PUEDEN SER
        PROTOCOL_CONNECTION_LOST: 'PROTOCOL_CONNECTION_LOST',
        ER_CON_COUNT_ERROR: ' ER_CON_COUNT_ERROR',
        ECONNREFUSED: 'ECONNREFUSED',
        ER_ACCESS_DENIED_ERROR: 'ER_ACCESS_DENIED_ERROR',
        
    }
}